## Step 1 of the methylation provenance-verification plan
## (code/methylation_provenance_verification_plan.md).
##
## Frozen frontier: extdata/se_lab_tcga.rds + extdata/combmetadata.rds.
## Code under test: the existing production chain in hallberg2025.base/R/methylation.R
##   (read_methylation_data -> check_against_manifest -> update_tcga_barcodes -> drop_signet).
## Anchor: identical() against the committed hallberg2025.base/data/methylation_se.rda.

strip_basename_column <- function(se) {
  colData(se) <- colData(se)[, setdiff(colnames(colData(se)), "basename")]
  se
}

## Step 1: takes se_lab_tcga as a file path (frozen frontier).
regenerate_methylation_se <- function(combmetadata_file, se_lab_tcga_file,
                                       manifest, discordant,
                                       match_table_file, signet_file) {
  se <- hallberg2025.base:::read_methylation_data(combmetadata_file, se_lab_tcga_file)
  se <- hallberg2025.base:::check_against_manifest(se, manifest, discordant)
  match_table <- read.csv(match_table_file)
  se <- hallberg2025.base:::update_tcga_barcodes(se, match_table)
  se <- hallberg2025.base:::drop_signet(se, signet_file, match_table)
  strip_basename_column(se)
}

## Step 2: takes se_lab_tcga as an in-memory object (regenerated by
## build_se_lab_tcga()).  Avoids writing se_lab_tcga to disk mid-pipeline.
regenerate_methylation_se_from_obj <- function(se_lab_tcga, combmetadata_file,
                                                manifest, discordant,
                                                match_table_file, signet_file) {
  ## read_methylation_data normally reads both files; replicate its colData
  ## augmentation inline since we already have the SE in memory.
  metadata <- readRDS(combmetadata_file) %>%
    tibble::as_tibble() %>%
    dplyr::filter(grepl("^C", Sample_Name)) %>%
    dplyr::rename(lab_id = Sample_Name)
  metadata2 <- SummarizedExperiment::colData(se_lab_tcga) %>%
    tibble::as_tibble()
  md <- dplyr::left_join(metadata2, metadata, by = "lab_id") %>%
    dplyr::select(-c(Diagnosis, sampletype, Sample)) %>%
    magrittr::set_colnames(tolower(colnames(.))) %>%
    dplyr::mutate(t.n = substr(tumor, 1, 1))
  SummarizedExperiment::colData(se_lab_tcga) <- S4Vectors::DataFrame(md)
  colnames(se_lab_tcga) <- se_lab_tcga$lab_id

  se <- hallberg2025.base:::check_against_manifest(se_lab_tcga, manifest, discordant)
  match_table <- read.csv(match_table_file)
  se <- hallberg2025.base:::update_tcga_barcodes(se, match_table)
  se <- hallberg2025.base:::drop_signet(se, signet_file, match_table)
  strip_basename_column(se)
}

## Safeguard B (direct intermediate check) + D (order-insensitive) for Step 2:
## compare the regenerated se_lab_tcga against its frozen twin
## (extdata/se_lab_tcga.rds) WITHOUT relying on physical row/col order. This
## localizes a fault to the build_se_lab_tcga() layer before it propagates to
## the leaf. Step 2 is deterministic arithmetic (subset/cbind/divide) so the
## beta assay is expected EXACT (tol = 0); colData labels are the Change-002
## surface, compared per-sample by lab_id.
compare_se_lab_tcga <- function(regenerated, frozen_file, tol = 0) {
  frozen <- readRDS(frozen_file)
  same_dim  <- identical(dim(regenerated), dim(frozen))
  same_rows <- identical(sort(rownames(regenerated)), sort(rownames(frozen)))
  same_cols <- identical(sort(colnames(regenerated)), sort(colnames(frozen)))

  assay_max_absdiff <- NA_real_
  assays_equal <- NA
  coldata_equal <- NA
  if (same_rows && same_cols) {
    ro <- order(rownames(regenerated)); co <- order(colnames(regenerated))
    fr <- order(rownames(frozen));      fc <- order(colnames(frozen))
    a <- SummarizedExperiment::assay(regenerated, "beta")[ro, co, drop = FALSE]
    b <- SummarizedExperiment::assay(frozen,      "beta")[fr, fc, drop = FALSE]
    assay_max_absdiff <- max(abs(a - b), na.rm = TRUE)
    assays_equal <- assay_max_absdiff <= tol

    ## colData compared per-sample: sort both by lab_id, compare labeling cols.
    cd_r <- as.data.frame(SummarizedExperiment::colData(regenerated))
    cd_f <- as.data.frame(SummarizedExperiment::colData(frozen))
    cd_r <- cd_r[order(cd_r$lab_id), , drop = FALSE]
    cd_f <- cd_f[order(cd_f$lab_id), , drop = FALSE]
    cols <- intersect(colnames(cd_f), colnames(cd_r))
    rownames(cd_r) <- rownames(cd_f) <- NULL
    coldata_equal <- isTRUE(all.equal(cd_r[, cols, drop = FALSE],
                                      cd_f[, cols, drop = FALSE]))
  }
  list(
    same_dim          = same_dim,
    same_rownames_set = same_rows,
    same_colnames_set = same_cols,
    assay_max_absdiff = assay_max_absdiff,
    assays_equal      = isTRUE(assays_equal),
    coldata_equal     = isTRUE(coldata_equal)
  )
}

## Safeguard B/D for Step 4: compare the regenerated `orse` against its frozen
## twin (output/methylation.Rmd/se.rds) order-insensitively, before it
## propagates through build_se_lab_tcga() to the leaf. se.rds carries two
## integer-encoded assays (beta scaled x1000, M x100). Step 4 is deterministic
## arithmetic on the frozen matrices, so both assays are expected EXACT
## (tol = 0); any tolerance belongs at Step 5 (minfi), not here.
compare_orse <- function(regenerated, frozen_file, tol = 0) {
  frozen <- readRDS(frozen_file)
  same_dim  <- identical(dim(regenerated), dim(frozen))
  same_rows <- identical(sort(rownames(regenerated)), sort(rownames(frozen)))
  same_cols <- identical(sort(colnames(regenerated)), sort(colnames(frozen)))

  assay_max_absdiff <- stats::setNames(rep(NA_real_, 2), c("beta", "M"))
  assays_equal <- NA
  if (same_rows && same_cols) {
    ro <- order(rownames(regenerated)); co <- order(colnames(regenerated))
    fr <- order(rownames(frozen));      fc <- order(colnames(frozen))
    for (a in c("beta", "M")) {
      x <- SummarizedExperiment::assays(regenerated)[[a]][ro, co, drop = FALSE]
      y <- SummarizedExperiment::assays(frozen)[[a]][fr, fc, drop = FALSE]
      assay_max_absdiff[[a]] <- max(abs(x - y), na.rm = TRUE)
    }
    assays_equal <- all(assay_max_absdiff <= tol, na.rm = TRUE)
  }
  list(
    same_dim          = same_dim,
    same_rownames_set = same_rows,
    same_colnames_set = same_cols,
    assay_max_absdiff = assay_max_absdiff,
    assays_equal      = isTRUE(assays_equal)
  )
}

## Safeguard B for Step 5: compare a regenerated bVals/mVals matrix against its
## frozen twin. Unlike Steps 1-4, minfi/annotation-version drift can change probe
## MEMBERSHIP (detP + SNP + cross-reactive lists are version-dependent), so this
## reports set overlap AND the value diff on the shared probes/samples, and uses
## TOLERANCE rather than exactness. Interpret with the terminal gate: small
## per-cell diffs are acceptable only if they don't move a manuscript number.
compare_matrix <- function(regenerated, frozen_file, tol = 1e-6) {
  frozen <- readRDS(frozen_file)
  common_rows <- intersect(rownames(regenerated), rownames(frozen))
  common_cols <- intersect(colnames(regenerated), colnames(frozen))
  a <- regenerated[common_rows, common_cols, drop = FALSE]
  b <- frozen[common_rows, common_cols, drop = FALSE]
  ## M-values = log2(beta/(1-beta)); a beta hitting exactly 0/1 sends M to
  ## +/-Inf, and a sub-permille beta drift across minfi versions can flip a
  ## boundary cell's Inf-ness. Score the tolerance on jointly-finite cells and
  ## report the non-finite (Inf) disagreement count separately, rather than
  ## letting a single boundary flip poison max() to Inf. (For beta matrices,
  ## which are always finite in [0,1], n_nonfinite_mismatch is trivially 0 and
  ## finite_maxdiff is the ordinary max abs diff.)
  fin <- is.finite(a) & is.finite(b)
  finite_maxdiff <- if (any(fin)) max(abs(a[fin] - b[fin])) else NA_real_
  n_nonfinite_mismatch <- sum(is.finite(a) != is.finite(b))
  list(
    regenerated_dim      = dim(regenerated),
    frozen_dim           = dim(frozen),
    same_rownames_set    = setequal(rownames(regenerated), rownames(frozen)),
    same_colnames_set    = setequal(colnames(regenerated), colnames(frozen)),
    n_common_probes      = length(common_rows),
    n_common_samples     = length(common_cols),
    finite_maxdiff       = finite_maxdiff,
    n_nonfinite_mismatch = n_nonfinite_mismatch,
    within_tol           = isTRUE(finite_maxdiff <= tol) && n_nonfinite_mismatch == 0
  )
}

## Step-5 assurance: per-sample Pearson correlation between the regenerated and
## frozen beta matrices, on jointly-finite shared probes. Betas (not M) are the
## biological signal and are bounded in [0,1] with no Inf, so correlation is a
## clean, scale-robust summary of concordance under minfi funnorm version-drift --
## complementing compare_matrix()'s max|Δ| (which a single drifted probe can
## dominate). Reports every sample's r, the min/median, and whether all samples
## clear `threshold` (default 0.99, matching the documented Step-5 result:
## batch 1 r >= 0.992, batch 2 r >= 0.9997).
beta_cor <- function(regenerated, frozen_file, threshold = 0.99) {
  frozen <- readRDS(frozen_file)
  cr <- intersect(rownames(regenerated), rownames(frozen))
  cc <- intersect(colnames(regenerated), colnames(frozen))
  a <- regenerated[cr, cc, drop = FALSE]
  b <- frozen[cr, cc, drop = FALSE]
  r <- vapply(cc, function(s) {
    x <- a[, s]; y <- b[, s]
    ok <- is.finite(x) & is.finite(y)
    stats::cor(x[ok], y[ok])
  }, numeric(1))
  list(
    n_samples       = length(cc),
    n_common_probes = length(cr),
    min_r           = min(r),
    median_r        = stats::median(r),
    threshold       = threshold,
    all_above       = all(r > threshold),
    r               = sort(r)          # ascending: worst samples first
  )
}

verify_against_baseline <- function(regenerated, baseline_file) {
  e <- new.env()
  load(baseline_file, envir = e)
  baseline <- e$methylation_se
  is_identical <- identical(regenerated, baseline)
  list(
    identical = is_identical,
    same_dim = identical(dim(regenerated), dim(baseline)),
    same_colnames_set = identical(sort(colnames(regenerated)), sort(colnames(baseline))),
    same_rownames_set = identical(sort(rownames(regenerated)), sort(rownames(baseline))),
    assay_all_equal = if (!is_identical) {
      tryCatch(
        isTRUE(all.equal(SummarizedExperiment::assay(regenerated),
                          SummarizedExperiment::assay(baseline))),
        error = function(e) NA
      )
    } else {
      TRUE
    }
  )
}
